# Generated by Django 3.2.19 on 2023-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEnsurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ensurance_type', models.CharField(choices=[('GENERAL', 'Загальний'), ('VIP', 'Особливий'), ('LIMITED', 'Обмежений')], default='GENERAL', max_length=20, verbose_name='Тип медичного страхування')),
                ('person_unique_code', models.CharField(blank=True, help_text='Подається разом з заявою', max_length=10, null=True, verbose_name='Код РНОКПП особи')),
                ('person_fullname', models.CharField(blank=True, help_text='Вноситься вручну', max_length=255, null=True, verbose_name="Повне ім'я особи")),
                ('person_home_address', models.CharField(blank=True, help_text='Вноситься вручну', max_length=512, null=True, verbose_name='Домашня адреса')),
                ('person_medical_ensurance', models.CharField(blank=True, help_text='Вноситься вручну', max_length=512, null=True, verbose_name='Номер та дата медичного страхування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення інформації про запис')),
            ],
            options={
                'verbose_name': 'Медичне страхування',
                'verbose_name_plural': 'База медичного страхування',
                'ordering': ['id'],
            },
        ),
    ]
