# Generated by Django 3.2.19 on 2023-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry_info_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalensurance',
            name='person_unique_code',
            field=models.CharField(blank=True, help_text='Подається разом з заявою', max_length=10, null=True, unique=True, verbose_name='Код РНОКПП особи'),
        ),
    ]
